#define F_CPU 8000000UL
#define UART_BAUD 19200


#define LED_TOP_PORT C
#define LED_TOP_PIN 0
#define LED_TOP_RIGHT_PORT C
#define LED_TOP_RIGHT_PIN 1
#define LED_BOTTOM_RIGHT_PORT B
#define LED_BOTTOM_RIGHT_PIN 1
#define LED_BOTTOM_PORT B
#define LED_BOTTOM_PIN 2
#define LED_BOTTOM_LEFT_PORT B
#define LED_BOTTOM_LEFT_PIN 3
#define LED_TOP_LEFT_PORT B
#define LED_TOP_LEFT_PIN 5
#define LED_CENTER_PORT B
#define LED_CENTER_PIN 4

#define BUTTON_PORT D
#define BUTTON_PIN 3

#define USB_DETECT_PORT D
#define USB_DETECT_PIN 2

#define LINE_ENABLE_PORT B
#define LINE_ENABLE_PIN 6

#define CYFRAL_PULLUP_PORT B
#define CYFRAL_PULLUP_PIN 7

#define CYFRAL_REFERENCE_PORT B
#define CYFRAL_REFERENCE_PIN 0

